/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Page {
  page: number
  text: string
}
export interface TextChunk {
  id: number
  text: string
}
export declare function extractTextFromPdf(path: string): Promise<string>
export declare function extractTextPages(path: string): Promise<Array<Page>>
export declare function extractTextChunks(path: string, chunkSize: number, chunkOverlap: number): Promise<Array<TextChunk>>
